version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL:-blue}
      - BLUE_BACKEND=app_blue:3000
      - GREEN_BACKEND=app_green:3000
    command: ["/docker-entrypoint.sh"]
    depends_on:
      - app_blue
      - app_green
    networks:
      - app-network

  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:3000"
    environment:
      - PORT=3000
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:3000"
    environment:
      - PORT=3000
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
